### ISSUE TITLE
Instagram hesabı tavsiyesi: kod_evreni

### ISSUE THREAD

**Issue by menesdev** [musayazlik/tasarimcilar-ve-yazilimcilar-icin-kaynak-arsivim#1]
Çok beğendiğim ve istifade ettiğim bir Instagram hesabı bırakıyorum. Eklemeniz halinde çok fayda sağlayacaktır. :)
Paylaşımlarınız için teşekkürler.

https://www.instagram.com/kod_evreni/

**Comment by musayazlik** [comment]
Teşekkür ederim hocam. Yarın boş vaktimde eklemesini yaparım.
